spring: 
  datasource: 
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/msaTest1
    username: sa
    password: '{cipher}a3742b8232521260bdbb2c6f4e92f364935951f52b36f46ded32b5d37c2d2955'

token:    
  expirationTime: 86400000
  secret: asdfasdfasdfasdfasdfasdfasdfasdf

gateway:
  ip: 192.168.0.36
  # ip: 192.168.35.243