spring: 
  datasource: 
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/msaTest1
    username: sa
    password: sa

token:    
  expirationTime: 86400000
  secret: asdfasdfasdfasdfasdfasdfasdfasdf

gateway:
  ip: 192.168.0.36
  # ip: 192.168.35.243