spring: 
  datasource: 
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/msaTestdb1
    username: sa
    password: '{cipher}AQBBLeC6ETE6MJjGjk5MU0G1IGrjHySFRAvtf+qD9SsyBjoflwGM4ju1MLmyZzDs1jvF480VIDMm3LdIs7kTEMD6V4vWcipYhpi7+K+BSJ67aItMEzfOuvLXjupcEF863G5a7vzNSwJNa5kwrGnkUuqhg74/McURXH+chys8H5uexDgfxbthNKvUtDX6Wote2WRcc0G6A1iuNALB+x88Lwc1/8LXtlmSjKySW5ytZ6c2roAo6DTgd0ZtmMiSX78guzG7mLwW6/cwDVWA/iqH0wgi0UUlPsEuvlHBC1kqdTbBzjnVjdIlu7ofCVX/DFzLwLdAlrQ+g5pxzzo5Jab9LCeHlBFdYdJhH948Q/f/9YCzw0QI1mBpSivEjQasCSnJnoA='

token:    
  expirationTime: 86400000
  secret: '{cipher}AQByYDKn9fA6RUu9YVAJO2aWS5oGsE9Q6XH56v7xGKKpXllPPxIIr7cSbDJaivlc6+afO0DfEHQRwH3+ef/WfjgGix1Wl3+An8jyaCmNpcTwExB4tWB1Da+jb582KCNF3YWsHZtqNO2D1uC0fXb9bd/9Usvy54D7RrsaSrwDCXrdHmFKKbIuj7pY7LbRxN6JPRdeFXOuw/jxohczlMfTdSJiJUgFFyWmZzvRwGFleQCzI32nDfs9eVSDCJf++gokZjBgRNy/kQFOZ9GsXzSHasqipstDnx56pSh4xO/PcBVi/9IWKdVuGZr94Z6I2UUy9nEZbnIl7QDvAZ7t7icYL95ZHHMMwViiFi/lM3BWgx5sevQCazZr8m1eSeg775HBirgdf9dptc6VHJdc/vF6L7VC59YjpR1eNMo8/hyVJDnhCQ=='

gateway:
  # ip: 192.168.0.36
  ip: 192.168.35.243

order_service:
  url: http://ORDER-MICRO-SERVICE/order-micro-service/%s/orders
  exception:
    orders_is_empty: User's orders is empty